# Generated by Django 5.1.5 on 2025-02-03 17:14

import Capstone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0002_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=Capstone.models.directorio_usuario),
        ),
    ]
