# Generated by Django 5.1.5 on 2025-03-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0005_remove_file_description_file_tags_folder_file_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
